package com.myspace.pv207;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExchangeRate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String base;
	private java.util.HashMap rates;

	public ExchangeRate() {
	}

	public java.lang.String getBase() {
		return this.base;
	}

	public void setBase(java.lang.String base) {
		this.base = base;
	}

	public java.util.HashMap getRates() {
		return this.rates;
	}

	public void setRates(java.util.HashMap rates) {
		this.rates = rates;
	}

	public ExchangeRate(java.lang.String base, java.util.HashMap rates) {
		this.base = base;
		this.rates = rates;
	}

}