package com.myspace.pv207;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExchangeRate implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ExchangeRate() {
    }




}