package com.myspace.pv207;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Price")
	private java.lang.Integer price;

	@org.kie.api.definition.type.Label(value = "Currency")
	private java.lang.String currency;

	public Order() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public Order(java.lang.String name, java.lang.Integer price,
			java.lang.String currency) {
		this.name = name;
		this.price = price;
		this.currency = currency;
	}

}